#!/bin/sh
. /opt/farm/scripts/init

if grep -qFx $OSVER /opt/farm/ext/binary-ssh-client/config/use-wrapper.conf && [ ! -s /etc/local/.config/ssh-compat.disable ]; then
	arch=`/opt/farm/ext/system/detect-architecture.sh`
	path=/opt/farm/ext/binary-ssh-client/bin/ssh_debian_6.7p1-5+deb8u8/$arch
	LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$path/lib  "$path/scp" -S "$path/ssh" "$@"
else
	scp "$@"
fi
